# Generated by Django 3.0.8 on 2021-05-25 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                (
                    'thumbnail',
                    models.ImageField(default='default.png', upload_to='Thumbnails'),
                ),
                ('content', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, max_length=460, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
