# Generated by Django 3.0.8 on 2021-06-02 14:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
